package com.feetsdk.android.feetsdk.db.domain;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.feetsdk.android.feetsdk.db.domain.table.FavSong;
import com.feetsdk.android.feetsdk.db.domain.table.LocalSongs;

import com.feetsdk.android.feetsdk.db.domain.FavSongDao;
import com.feetsdk.android.feetsdk.db.domain.LocalSongsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favSongDaoConfig;
    private final DaoConfig localSongsDaoConfig;

    private final FavSongDao favSongDao;
    private final LocalSongsDao localSongsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favSongDaoConfig = daoConfigMap.get(FavSongDao.class).clone();
        favSongDaoConfig.initIdentityScope(type);

        localSongsDaoConfig = daoConfigMap.get(LocalSongsDao.class).clone();
        localSongsDaoConfig.initIdentityScope(type);

        favSongDao = new FavSongDao(favSongDaoConfig, this);
        localSongsDao = new LocalSongsDao(localSongsDaoConfig, this);

        registerDao(FavSong.class, favSongDao);
        registerDao(LocalSongs.class, localSongsDao);
    }
    
    public void clear() {
        favSongDaoConfig.clearIdentityScope();
        localSongsDaoConfig.clearIdentityScope();
    }

    public FavSongDao getFavSongDao() {
        return favSongDao;
    }

    public LocalSongsDao getLocalSongsDao() {
        return localSongsDao;
    }

}
